project:
  name: "Okkur Labs Website"
  state: "stable"
  image: "https://github.com/okkur/website/blob/master/static/images/logo.svg"
  website: "https://okkur.org"
  oneLiner: "Sustainable. Open Source. Community."
  description: |
    Okkur Labs website repository for the static website hosted at https://about.okkur.org.  
    Built with [Hugo](https://gohugo.io) and [Syna](https://syna.okkur.org).
  version: "v0.1.0"
  mainLicense: "CCByNcSa"

vision:
  type: "community"
  overview: |
    Website to showcase Okkur Labs.
contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/okkur/website/labels/starter%20issue"

emails:
  security: "security@okkur.org"
  coc: "coc@okkur.org"

copyright:
  year: "2018"

cla:
  copyrightHolder: "nzt.ventures GmbH"
  mail: "legal@nzt.ventures"

maintainers:
  - name: "Michael Grosser"
    nick: "stp-ip"

repo:
  link: "https://git.okkur.org/website"
  type: "Github"

badges:
  - image: "https://img.shields.io/badge/state-stable-green.svg"
    alt: "state"
  - image: "https://img.shields.io/github/license/okkur/website.svg"
    link: "LICENSE"
    alt: "license"

reposeed:
  configVersion: "v1"
