# Site settings
baseurl = "https://about.okkur.io/"
languageCode = "en-us"
title = "Sustainable open source research"
theme = "syna"
version = "0.3.0"
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

DefaultContentLanguage = "en"

[params]
  name = "Okkur Labs"
  description = "Sustainable open source research"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32 48x48"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://stats.okkur.net"
    id = "14"
    domain = "about.okkur.io" # Track subdomains via "*.example.com"

[[menu.main]]
  url = "#txtdirect"
  name = "TXTDirect"
  weight = 10

[[menu.main]]
  url = "/syna"
  name = "Syna"
  weight = 20

[[menu.main]]
  url = "#resumic"
  name = "Resumic"
  weight = 30

[[menu.main]]
  url = "/subscription/"
  name = "Subscription"
  weight = 40


[[menu.copyright_footer]]
  url = "/projects/"
  name = "Further projects"
  weight = 10

[[menu.copyright_footer]]
  url = "/imprint"
  name = "Imprint"
  weight = 20
