# Site settings
baseurl = "https://about.okkur.org/"
languageCode = "en-us"
title = "Sustainable Open Source"
theme = "syna"
version = "0.2.0"
enableGitInfo = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

DefaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

  # disable highlighting until #672 is fixed
  [markup.highlight]
    codeFences = false

[params]
  name = "Okkur Labs"
  description = "Sustainable Open Source"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32 48x48"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://stats.okkur.net"
    id = "14"
    domain = "about.okkur.org" # Track subdomains via "*.example.com"

[[menu.main]]
  url = "/syna"
  name = "Syna"
  weight = 10

[[menu.main]]
  url = "#txtdirect"
  name = "TXTDirect"
  weight = 20

[[menu.main]]
  url = "#resumic"
  name = "Resumic"
  weight = 30

[[menu.main]]
  url = "/sustain/"
  name = "Sponsor & Sustain"
  weight = 40

#[[menu.main]]
#  url = "https://blog.okkur.org"
#  name = "Blog"
#  weight = 50

[[menu.copyright_footer]]
  url = "/projects/"
  name = "Further projects"
  weight = 10

[[menu.copyright_footer]]
  url = "/imprint"
  name = "Imprint"
  weight = 20
