# Site settings
baseurl = "https://about.okkur.io/"
languageCode = "en-us"
title = "Sustainable open source research"
theme = "syna"
version = "0.2.0"

DefaultContentLanguage = "en"

[params]
  name = "Okkur Labs"
  description = "Sustainable open source research"
  image = "header-min.jpg"

  # Branding options
  [params.branding]
    logoNavigation = "logo.svg"
    textNavigation = "Okkur Labs"

  [params.style]
    backgroundNavigation = "light"
    backgroundFooter = "dark"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    faviconICOSizes = "16x16 32x32"
    faviconPNG = "favicon.png"
    faviconSVG = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://stats.seetheprogress.com"
    id = "14"
    domain = "about.okkur.io" # Track subdomains via "*.example.com"

  [params.contact]
    disabled = true

[[menu.main]]
  url = "#txtdirect"
  name = "TXTDirect"
  weight = 10

[[menu.main]]
  url = "#reposeed"
  name = "Reposeed"
  weight = 20

[[menu.main]]
  url = "#syna"
  name = "Syna"
  weight = 30

[[menu.legalFooter]]
  url = "/about"
  name = "About Us"
  weight = 10
